sudo: required
dist: trusty
language: java

matrix:
  include:
    - os: linux
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk10
  - openjdk11  

before_install:
  - sudo apt-get update

install:
  - ls .
  - ls ..
  - cd .. && git clone https://github.com/micwypych/jpf-config
  - jpf-config/script.sh
  - cd java-with-jpf-example

script:
  - pwd
  - ./gradlew test
  

notifications:
  email: false
